export type QuestionType = 'select' | 'multiselect' | 'scale' | 'text';

export interface Question {
  id: string;
  text: string;
  type: QuestionType;
  options?: string[];
  scaleMin?: number;
  scaleMax?: number;
  scaleLabels?: { min: string; max: string };
  required?: boolean;
}

export interface Persona {
  id: string;
  title: string;
  description: string;
  questions: Question[];
}

export const personas: Persona[] = [
  {
    id: 'student',
    title: 'Student / Early-Career Professional',
    description: 'Currently job searching or early in your career',
    questions: [
      {
        id: 'student_job_search_frustration',
        text: 'How would you describe your current job search experience?',
        type: 'select',
        options: [
          'Mostly positive - getting responses and interviews',
          'Mixed - some responses but lots of silence',
          'Frustrating - very few responses despite many applications',
          'Exhausting - feels like shouting into a void',
        ],
        required: true,
      },
      {
        id: 'student_application_volume',
        text: 'Roughly how many job applications have you submitted in the last 3 months?',
        type: 'select',
        options: [
          'Less than 10',
          '10-25',
          '26-50',
          '51-100',
          'More than 100',
        ],
        required: true,
      },
      {
        id: 'student_response_rate',
        text: 'Of those applications, how many led to a conversation with an actual person?',
        type: 'select',
        options: [
          'None',
          '1-2',
          '3-5',
          '6-10',
          'More than 10',
        ],
        required: true,
      },
      {
        id: 'student_biggest_challenge',
        text: 'What\'s the most frustrating part of finding opportunities?',
        type: 'multiselect',
        options: [
          'Applications disappear into a black hole',
          'Can\'t get past automated screening systems',
          'Entry-level jobs require years of experience',
          'No way to stand out from other candidates',
          'Don\'t know the right people',
          'Unclear what employers actually want',
        ],
        required: true,
      },
      {
        id: 'student_current_tools',
        text: 'What are you currently using to find opportunities?',
        type: 'multiselect',
        options: [
          'LinkedIn',
          'Indeed / Job boards',
          'Company websites directly',
          'University career services',
          'Personal network / referrals',
          'Recruiters',
          'Cold outreach',
        ],
        required: true,
      },
      {
        id: 'student_networking_experience',
        text: 'Have you tried networking to find opportunities? How did that go?',
        type: 'select',
        options: [
          'Haven\'t really tried networking',
          'Tried but felt awkward or didn\'t know where to start',
          'Some success but hard to maintain connections',
          'Networking has been my most effective approach',
        ],
        required: true,
      },
      {
        id: 'student_ideal_help',
        text: 'What would actually help you most right now?',
        type: 'select',
        options: [
          'Help applying to more jobs faster',
          'Better resume/application optimization',
          'Connections to people who can refer me',
          'Mentorship from people in my target field',
          'Visibility into companies actually hiring',
        ],
        required: true,
      },
      {
        id: 'student_local_preference',
        text: 'How important is it that job opportunities are local to your area?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Don\'t care - remote is fine', max: 'Strongly prefer local' },
        required: true,
      },
      {
        id: 'student_sms_comfort',
        text: 'How comfortable would you be receiving career help through text messages instead of another app?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Not comfortable', max: 'Very comfortable' },
        required: true,
      },
      {
        id: 'student_community_connection',
        text: 'Do you feel connected to any professional community in your area right now?',
        type: 'select',
        options: [
          'Yes, I\'m actively involved in local professional groups',
          'Somewhat - I know a few people but not deeply connected',
          'Not really - I don\'t know many professionals locally',
          'No - I\'m mostly looking at remote/national opportunities anyway',
        ],
        required: true,
      },
      {
        id: 'student_pain_intensity',
        text: 'How much does your current job search situation stress you out?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 10,
        scaleLabels: { min: 'Not stressful', max: 'Extremely stressful' },
        required: true,
      },
    ],
  },
  {
    id: 'mentor',
    title: 'Mentor / Advisor',
    description: 'Experienced professional interested in helping others',
    questions: [
      {
        id: 'mentor_experience',
        text: 'Have you mentored someone before (formally or informally)?',
        type: 'select',
        options: [
          'Yes, I actively mentor people regularly',
          'Yes, occasionally when asked',
          'I\'ve helped people informally but not structured mentoring',
          'No, but I\'d like to',
          'No, and I\'m not sure it\'s for me',
        ],
        required: true,
      },
      {
        id: 'mentor_motivation',
        text: 'What draws you to mentoring or helping others professionally?',
        type: 'multiselect',
        options: [
          'Want to give back to my community',
          'Enjoy watching others grow and succeed',
          'Wish I had more help when I was starting out',
          'It helps me stay sharp and learn too',
          'Professional obligation / part of my role',
          'Building my network and reputation',
        ],
        required: true,
      },
      {
        id: 'mentor_blockers',
        text: 'What has stopped you from mentoring more?',
        type: 'multiselect',
        options: [
          'Don\'t have enough time',
          'Don\'t know how to find people who need help',
          'Unsure if I\'m qualified to mentor',
          'Bad experiences with uncommitted mentees',
          'Too much friction in scheduling and logistics',
          'Nothing - I mentor as much as I want to',
        ],
        required: true,
      },
      {
        id: 'mentor_current_requests',
        text: 'How do people currently find you when they want advice?',
        type: 'multiselect',
        options: [
          'Cold LinkedIn messages',
          'Through mutual connections',
          'Formal mentorship programs',
          'They don\'t - I\'m not visible as a potential mentor',
          'Through my content/posts online',
          'Work colleagues',
        ],
        required: true,
      },
      {
        id: 'mentor_cold_outreach_feeling',
        text: 'When someone reaches out cold asking for help, how do you typically feel?',
        type: 'select',
        options: [
          'Happy to help if they seem genuine',
          'Depends entirely on how they approach me',
          'Usually skeptical or annoyed',
          'Overwhelmed - too many requests to handle',
          'Rarely happens to me',
        ],
        required: true,
      },
      {
        id: 'mentor_time_commitment',
        text: 'If connecting with the right mentees was effortless, how much time would you realistically give to mentoring per month?',
        type: 'select',
        options: [
          'Less than 1 hour',
          '1-2 hours',
          '3-5 hours',
          '5-10 hours',
          'More than 10 hours',
        ],
        required: true,
      },
      {
        id: 'mentor_auto_matching_interest',
        text: 'How would you feel about a platform that automatically matched you with people who need your specific expertise?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Not interested', max: 'Very interested' },
        required: true,
      },
      {
        id: 'mentor_impact_tracking',
        text: 'Would it matter to you to see whether your advice actually helped someone over time?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Not important', max: 'Very important' },
        required: true,
      },
      {
        id: 'mentor_local_preference',
        text: 'Does it matter to you whether the person you\'re helping is in your local area?',
        type: 'select',
        options: [
          'Yes - I prefer helping people locally',
          'Somewhat - local feels more meaningful',
          'Doesn\'t matter - happy to help anyone',
          'Actually prefer remote - more flexibility',
        ],
        required: true,
      },
      {
        id: 'mentor_sms_calendar_comfort',
        text: 'How comfortable would you be with automated introductions via text and direct calendar booking?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Not comfortable', max: 'Very comfortable' },
        required: true,
      },
      {
        id: 'mentor_guilt',
        text: 'Do you ever feel like you should be doing more to help others in your field?',
        type: 'select',
        options: [
          'Yes, often',
          'Sometimes',
          'Rarely',
          'No - I\'m doing what I can',
        ],
        required: true,
      },
    ],
  },
  {
    id: 'employer',
    title: 'Employer / Hiring Manager',
    description: 'Responsible for hiring or building teams',
    questions: [
      {
        id: 'employer_hiring_challenge',
        text: 'What\'s the hardest part of hiring right now?',
        type: 'multiselect',
        options: [
          'Too many unqualified applicants to filter through',
          'Can\'t find candidates with the right skills',
          'Good candidates get scooped up by competitors',
          'Hard to assess culture fit before hiring',
          'Recruiting is too expensive',
          'Don\'t have visibility into local talent',
        ],
        required: true,
      },
      {
        id: 'employer_application_volume',
        text: 'For a typical role, roughly how many applications do you receive?',
        type: 'select',
        options: [
          'Less than 25',
          '25-50',
          '51-100',
          '101-250',
          'More than 250',
        ],
        required: true,
      },
      {
        id: 'employer_bad_hire_experience',
        text: 'Have you ever made a hire that looked great on paper but didn\'t work out?',
        type: 'select',
        options: [
          'Yes, multiple times',
          'Yes, once or twice',
          'No, but I\'ve come close',
          'No, our process catches these',
        ],
        required: true,
      },
      {
        id: 'employer_referral_importance',
        text: 'How important are referrals compared to inbound applications in your hiring?',
        type: 'select',
        options: [
          'Referrals are our primary source of good hires',
          'Referrals are preferred but we hire from applications too',
          'We treat them equally',
          'We mostly hire from applications/job boards',
        ],
        required: true,
      },
      {
        id: 'employer_current_tools',
        text: 'What tools or platforms are you using to find candidates?',
        type: 'multiselect',
        options: [
          'LinkedIn / LinkedIn Recruiter',
          'Indeed / Job boards',
          'Recruiting agencies',
          'Employee referral programs',
          'University partnerships',
          'Our own network/connections',
          'Applicant tracking systems (ATS)',
        ],
        required: true,
      },
      {
        id: 'employer_trajectory_interest',
        text: 'If you could see a candidate\'s growth trajectory over time (contributions, mentorship, community involvement), would that change how you evaluate them?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Wouldn\'t matter', max: 'Very valuable' },
        required: true,
      },
      {
        id: 'employer_warm_intro_preference',
        text: 'Would you prefer warm introductions to candidates through a local network vs. cold applications?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Prefer cold applications', max: 'Strongly prefer warm intros' },
        required: true,
      },
      {
        id: 'employer_local_importance',
        text: 'How important is it that candidates are local or embedded in your community?',
        type: 'select',
        options: [
          'Critical - we only hire locally',
          'Preferred - but open to remote',
          'Doesn\'t matter - skills are what count',
          'We\'re fully remote - location irrelevant',
        ],
        required: true,
      },
      {
        id: 'employer_current_spend',
        text: 'Roughly what do you spend annually on recruiting (job boards, recruiters, tools)?',
        type: 'select',
        options: [
          'Less than $5,000',
          '$5,000 - $15,000',
          '$15,000 - $50,000',
          '$50,000 - $100,000',
          'More than $100,000',
          'Not sure',
        ],
        required: true,
      },
      {
        id: 'employer_bad_hire_cost',
        text: 'If you could reduce bad hires by 20%, how valuable would that be to you?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 10,
        scaleLabels: { min: 'Minimal value', max: 'Extremely valuable' },
        required: true,
      },
      {
        id: 'employer_satisfaction',
        text: 'How satisfied are you with your current recruiting process?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Very dissatisfied', max: 'Very satisfied' },
        required: true,
      },
    ],
  },
  {
    id: 'program_director',
    title: 'Program Director',
    description: 'Running workforce, mentorship, or community programs',
    questions: [
      {
        id: 'program_type',
        text: 'What type of programs do you run?',
        type: 'multiselect',
        options: [
          'Workforce development',
          'Mentorship programs',
          'Career readiness / job placement',
          'Professional networking',
          'Skills training',
          'Community building',
          'Youth programs',
        ],
        required: true,
      },
      {
        id: 'program_success_measurement',
        text: 'How do you currently measure success?',
        type: 'multiselect',
        options: [
          'Attendance / participation numbers',
          'Completion rates',
          'Job placement outcomes',
          'Participant surveys / satisfaction',
          'Long-term outcome tracking',
          'We struggle to measure meaningful outcomes',
        ],
        required: true,
      },
      {
        id: 'program_data_challenge',
        text: 'What\'s the hardest thing to prove about your program\'s impact?',
        type: 'multiselect',
        options: [
          'That relationships actually formed',
          'Long-term outcomes after program ends',
          'Quality of engagement (not just attendance)',
          'Attribution - did our program cause the outcome?',
          'ROI for funders',
          'Nothing - we have good data',
        ],
        required: true,
      },
      {
        id: 'program_tracking_method',
        text: 'How are you tracking mentorship or networking activity today?',
        type: 'select',
        options: [
          'Manual tracking (spreadsheets, forms)',
          'Dedicated software platform',
          'CRM system',
          'We don\'t track this well',
          'Participants self-report',
        ],
        required: true,
      },
      {
        id: 'program_reporting_time',
        text: 'How much time do you spend on tracking and reporting each month?',
        type: 'select',
        options: [
          'Less than 2 hours',
          '2-5 hours',
          '5-10 hours',
          '10-20 hours',
          'More than 20 hours',
        ],
        required: true,
      },
      {
        id: 'program_funding_pressure',
        text: 'Have you ever lost funding or had to fight for it because you couldn\'t show results?',
        type: 'select',
        options: [
          'Yes, we\'ve lost funding over this',
          'Yes, we\'ve had difficult conversations with funders',
          'Not yet, but it\'s a constant worry',
          'No, our funders are satisfied with current metrics',
        ],
        required: true,
      },
      {
        id: 'program_dashboard_interest',
        text: 'If you had a dashboard showing real engagement data (sessions happening, relationships forming, goals hit), how valuable would that be?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 10,
        scaleLabels: { min: 'Not valuable', max: 'Extremely valuable' },
        required: true,
      },
      {
        id: 'program_passive_tracking_interest',
        text: 'Would it be valuable if participant activity was automatically tracked (via text/calendar) instead of manually reported?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Not valuable', max: 'Very valuable' },
        required: true,
      },
      {
        id: 'program_current_budget',
        text: 'What\'s your annual budget for tools that support participant engagement?',
        type: 'select',
        options: [
          'Less than $1,000',
          '$1,000 - $3,000',
          '$3,000 - $10,000',
          '$10,000 - $25,000',
          'More than $25,000',
          'No dedicated budget for this',
        ],
        required: true,
      },
      {
        id: 'program_willingness_to_pay',
        text: 'Would you pay $3,000/year for a tool that could prove your program\'s value to funders and save 10+ hours/month on reporting?',
        type: 'select',
        options: [
          'Yes, absolutely',
          'Probably, if we could see it work first',
          'Maybe, would need to think about it',
          'Unlikely - budget is too tight',
          'No - we have other solutions',
        ],
        required: true,
      },
      {
        id: 'program_attendance_sufficient',
        text: 'Is attendance tracking alone sufficient for your funders, or do they want deeper engagement data?',
        type: 'select',
        options: [
          'Attendance is enough for now',
          'They ask for more but accept what we have',
          'They want deeper data but we can\'t provide it',
          'They require engagement/outcome data',
        ],
        required: true,
      },
    ],
  },
  {
    id: 'coach',
    title: 'Coach / Solopreneur',
    description: 'Running your own coaching or consulting practice',
    questions: [
      {
        id: 'coach_practice_type',
        text: 'What type of coaching or consulting do you do?',
        type: 'multiselect',
        options: [
          'Executive/leadership coaching',
          'Career coaching',
          'Business/startup coaching',
          'Life coaching',
          'Skills-based training',
          'Consulting/advisory',
          'Group programs/masterminds',
        ],
        required: true,
      },
      {
        id: 'coach_client_acquisition',
        text: 'How do you currently find clients?',
        type: 'multiselect',
        options: [
          'Referrals from past clients',
          'Social media / content marketing',
          'Networking events',
          'Partnerships with organizations',
          'Paid advertising',
          'Cold outreach',
          'It\'s a struggle - always looking for better ways',
        ],
        required: true,
      },
      {
        id: 'coach_sales_challenge',
        text: 'What\'s the hardest part of selling your services?',
        type: 'multiselect',
        options: [
          'Proving ROI to potential clients',
          'Justifying premium pricing',
          'Standing out from other coaches',
          'Finding qualified leads',
          'Converting leads to paying clients',
          'Nothing - sales isn\'t my bottleneck',
        ],
        required: true,
      },
      {
        id: 'coach_progress_tracking',
        text: 'How do you currently track client progress?',
        type: 'select',
        options: [
          'Detailed tracking system/software',
          'Notes and informal check-ins',
          'Client self-reporting',
          'I don\'t track progress systematically',
        ],
        required: true,
      },
      {
        id: 'coach_transformation_proof',
        text: 'Do you have documented proof of client transformations you can show prospects?',
        type: 'select',
        options: [
          'Yes, with data and case studies',
          'Some testimonials but no hard data',
          'Informal success stories only',
          'No - this is a gap for me',
        ],
        required: true,
      },
      {
        id: 'coach_tech_stack_satisfaction',
        text: 'How satisfied are you with your current tech stack for running your practice?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 5,
        scaleLabels: { min: 'Very frustrated', max: 'Works great' },
        required: true,
      },
      {
        id: 'coach_tool_count',
        text: 'How many different tools do you use to run your coaching business?',
        type: 'select',
        options: [
          '1-2 tools',
          '3-5 tools',
          '6-10 tools',
          'More than 10 tools',
          'Too many - it\'s overwhelming',
        ],
        required: true,
      },
      {
        id: 'coach_transformation_tracking_interest',
        text: 'If a platform automatically tracked your clients\' goals and progress, creating proof of transformation you could show prospects, how valuable would that be?',
        type: 'scale',
        scaleMin: 1,
        scaleMax: 10,
        scaleLabels: { min: 'Not valuable', max: 'Extremely valuable' },
        required: true,
      },
      {
        id: 'coach_current_tool_spend',
        text: 'What do you currently spend monthly on tools to run your coaching business?',
        type: 'select',
        options: [
          'Less than $50',
          '$50 - $100',
          '$100 - $250',
          '$250 - $500',
          'More than $500',
        ],
        required: true,
      },
      {
        id: 'coach_consolidation_interest',
        text: 'Would you pay more for an all-in-one platform that handled community, tracking, and proof of results?',
        type: 'select',
        options: [
          'Yes - consolidation is worth paying for',
          'Maybe - depends on the price and features',
          'Probably not - I like my current setup',
          'No - I prefer best-of-breed tools',
        ],
        required: true,
      },
      {
        id: 'coach_group_programs',
        text: 'Do you run (or want to run) group programs, masterminds, or communities?',
        type: 'select',
        options: [
          'Yes, it\'s a core part of my business',
          'Yes, but it\'s hard to manage',
          'I want to but haven\'t figured out how',
          'No, I focus on 1:1 work',
        ],
        required: true,
      },
    ],
  },
];
